### ISSUE TITLE
Bakar mısın ?

### ISSUE THREAD

**Issue by DogancanYr** [yasircoskun/chaos#1]
Bunu görmüştüm githubunuzda https://gist.github.com/yasircoskun/68187fc854331e13f745d691dfd3f754 ama tersini yapabilmeniz mümkün mü?

**Comment by yasircoskun** [comment]
TurkAnime anime sayfasında dış bağlantılar kısmına bakarsanız zaten hemen hemen hepsi için MyAnimeList bağlantısı olduğunu görebilirsiniz.

Gerekli olduğuna ikna edilirsem yapabilirim.

**Comment by DogancanYr** [comment]
> TurkAnime anime sayfasında dış bağlantılar kısmına bakarsanız zaten hemen hemen hepsi için MyAnimeList bağlantısı olduğunu görebilirsiniz.
> 
> Gerekli olduğuna ikna edilirsem yapabilirim.

Gördüm ama takip listesinde aşırı fazla anime olduğu için tek tek yapmam mümkün değil ve 720p veya 1080p yazsada kalite olarak bitratesi düşük olduğu için düşük çözünürlükte oynatıyor genelde altyazıyı yapan sitelerden izliyorum ve artık kullanmak istemiyorum siteyi .Anime listelerini kaydetmek için evrensel bir siteyi kullanmayı tercih etmek istemiştim .

**Comment by DogancanYr** [comment]
İkna edebildim mi seni ?
